spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
     url: jdbc:mysql://localhost:3306/jpa?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
     username: root
     password: root